name: voice_recognition_mo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  modal_progress_hud_nsn: ^0.4.0
  http: ^1.1.0
  record: ^5.0.1
  google_speech: ^4.1.0
  permission_handler: ^10.3.0
  audioplayers: ^5.2.0
  path_provider: ^2.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/audioSample.wav
    - assets/serviceAccount.json

uses-material-design: true

